#!/usr/bin/sh


PATCH_MARKER=/mnt/nvidia/driver/.patched-marker

# Needs to run before the bind mount as that changes the libs required by git to run properly
# and risks host curruption.
clone_repo() {
    echo "[INFO] Cloning nvidia patch script"
    git clone https://github.com/keylase/nvidia-patch.git
}

# Needs to run before the patch script as we need write access to libs.
bind_mount() {
    echo "[INFO] mounting nvidia libraries"
    mount --bind /mnt/nvidia/driver/usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
}

bind_unmount() {
    echo '[INFO] restoring original libraries'
    umount /usr/lib/x86_64-linux-gnu
}

patch_driver() {
    echo '[INFO] patching NVENC driver'
    ./nvidia-patch/patch.sh
    touch $PATCH_MARKER
}

cleanup() {
    echo "[INFO] Caught termination signal. Exiting..."
    kill -KILL "$pid" 2>/dev/null
    exit 0
}
trap cleanup HUP INT QUIT PIPE TERM


init() {
    clone_repo
    bind_mount
    patch_driver
    echo "[INFO] Sleeping to keep pod alive..."
    sleep infinity &
    pid=$!
    wait
}

init
